"""EAG-specific Cypher query templates.

All queries use $param placeholders. No string concatenation with user input.
"""

from primitives.eag.queries.cluster import (
    BATCH_CREATE_MEMBER_OF,
    BATCH_UPDATE_NODE_IMPORTANCE,
    COUNT_CLUSTERS,
    CREATE_CLUSTER,
    CREATE_PART_OF,
    DELETE_CLUSTERS,
    GET_CLUSTER,
    GET_CLUSTER_MEMBERS,
    GET_CLUSTER_PARENT,
    GET_NODE_CLUSTERS,
    LIST_CLUSTERS,
    RUN_LEIDEN,
    RUN_PAGERANK,
    UPDATE_CLUSTER_SUMMARY,
)
from primitives.eag.queries.ddl import (
    ALL_CONTEXT_SERVICE_DDL,
    CLUSTER_INDEX_QUERIES,
    CUSTODIAN_DDL_STATEMENTS,
    ENGINE_INDEX_QUERIES,
    ENTITY_INDEX_QUERIES,
    FINDING_CLUSTER_INDEX,
    FINDING_CLUSTER_SCOPE_UNIQUE,
    FINDING_HISTORY_PASS_INDEX,
    FINDING_ORG_SCOPE_INDEX,
    FINDING_SILO_INDEX,
    PASS_ID_INDEX,
    PASS_SILO_INDEX,
    REFERENCE_ORG_INDEX,
    REFERENCE_URL_INDEX,
)
from primitives.eag.queries.finding import (
    FETCH_CURRENT_FINDING_CLUSTER_SCOPE,
    FETCH_CURRENT_FINDING_SILO_SCOPE,
    FINDING_HISTORY_CREATE,
    FINDING_HISTORY_TRIM,
    FINDING_MERGE_CLUSTER_SCOPE,
    FINDING_MERGE_SILO_SCOPE,
)
from primitives.eag.queries.pass_ledger import (
    PASS_CHECK_CLAIMED,
    PASS_CLAIMED_EDGE_MERGE,
    PASS_CREATE,
    PASS_FINALIZE,
    PASS_GET_BY_ID,
)
from primitives.eag.queries.silo import (
    CREATE_SILO,
    DELETE_SILO,
    GET_SILO,
    LIST_SILOS,
    RESET_SILO,
    UPDATE_SILO,
)

__all__ = [
    # silo
    "CREATE_SILO",
    "GET_SILO",
    "LIST_SILOS",
    "UPDATE_SILO",
    "DELETE_SILO",
    "RESET_SILO",
    # cluster
    "CREATE_CLUSTER",
    "GET_CLUSTER",
    "LIST_CLUSTERS",
    "COUNT_CLUSTERS",
    "DELETE_CLUSTERS",
    "UPDATE_CLUSTER_SUMMARY",
    "BATCH_CREATE_MEMBER_OF",
    "CREATE_PART_OF",
    "GET_CLUSTER_MEMBERS",
    "GET_NODE_CLUSTERS",
    "GET_CLUSTER_PARENT",
    "RUN_LEIDEN",
    "RUN_PAGERANK",
    "BATCH_UPDATE_NODE_IMPORTANCE",
    # ddl
    "ENGINE_INDEX_QUERIES",
    "CLUSTER_INDEX_QUERIES",
    "ENTITY_INDEX_QUERIES",
    "CUSTODIAN_DDL_STATEMENTS",
    "ALL_CONTEXT_SERVICE_DDL",
    "FINDING_CLUSTER_SCOPE_UNIQUE",
    "FINDING_ORG_SCOPE_INDEX",
    "FINDING_SILO_INDEX",
    "FINDING_CLUSTER_INDEX",
    "FINDING_HISTORY_PASS_INDEX",
    "PASS_ID_INDEX",
    "PASS_SILO_INDEX",
    "REFERENCE_ORG_INDEX",
    "REFERENCE_URL_INDEX",
    # finding
    "FETCH_CURRENT_FINDING_CLUSTER_SCOPE",
    "FETCH_CURRENT_FINDING_SILO_SCOPE",
    "FINDING_MERGE_CLUSTER_SCOPE",
    "FINDING_MERGE_SILO_SCOPE",
    "FINDING_HISTORY_CREATE",
    "FINDING_HISTORY_TRIM",
    # pass_ledger
    "PASS_CREATE",
    "PASS_FINALIZE",
    "PASS_CHECK_CLAIMED",
    "PASS_GET_BY_ID",
    "PASS_CLAIMED_EDGE_MERGE",
]
